spring:
  profiles:
    active: dev
# Set belows to your application-dev.yaml profile
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      base-url: ${OPENAI_BASE_URL}
#    chat:
#      client:
#        enabled: false