server:
  port: 7070
spring:
  ai:
    openai:
      api-key: <api-key>
      base-url: <https://api.com>
    mcp:
      client:
        name: spring-ai-mcp-client
        version: 1.0.0
        request-timeout: 30s
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8080
            server2:
              url: http://env-cvpjbjem1hkjat42sk4g-ap-southeast-1.alicloudapi.com/mcp-quark

logging:
  level:
    io:
      modelcontextprotocol:
        client: warn
        spec: warn