spring:
  ai:
    openai:
      api-key: <api-key>
      base-url: <https://api.com>
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: sync
        toolcallback:
          enabled: false
        stdio:
          servers-configuration: classpath:mcp-servers-config.json

logging:
  level:
    io:
      modelcontextprotocol:
        client: warn
        spec: warn