server:
  port: 7071

spring:
  datasource:
    url: jdbc:postgresql://xxx.com/postgres
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: sk-
      base-url: https://api
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

logging:
  level:
    io:
      modelcontextprotocol:
        client: warn
        spec: warn
    org:
      springframework:
        ai: debug
    root: debug
